### ISSUE TITLE
(Nice to have) Add min village pop to inactive finder

### ISSUE THREAD

**Issue by OneManDevz** [scriptworld-git/king-bot-api#26]
So it will find only some juicy inactives.

**Comment by didadadida93** [comment]
https://gist.github.com/didadadida93/ddc16beaa8ad6e04e245440f9d4e1319

**Comment by scriptworld-git** [comment]
thanks @didadadida93 !! nice work ! ill update that in the interface today and on the service :)

**Comment by scriptworld-git** [comment]
added
