### ISSUE TITLE
iron on raise fields page is zero

### ISSUE THREAD

**Issue by pepeverde9** [scriptworld-git/king-bot-api#45]
Hi
I noticed that whatever  I enter as iron value on the raise fields page, the next time I open this page, the iron value is always zero.

**Comment by scriptworld-git** [comment]
hey !
thanks for submitting,

could you please send a screenshot of the logging page AFTER you tried to set the iron fields to a number ?

I will also check this issue now :)

**Comment by scriptworld-git** [comment]
@pepeverde9 fixed this issue ! thanks for mentioning this, it was a little mistake I made.
